//-----------------------------------------------------------------------------
// FlexiRfaCommand.cs
//
// Creates a new rotatable family from a template, or edits the nested
// "3D Orientation Family" geometry of an existing rotatable family instance.
// Ported from the ProofOfConcept sample.
//-----------------------------------------------------------------------------

namespace FlexiRfa;

public class FlexiRfaCommand : IRevitExtension<FlexiRfaArgs>
{
    public IExtensionResult Run(IRevitExtensionContext context, FlexiRfaArgs args, CancellationToken cancellationToken)
    {
        var activeDocument = context.UIApplication.ActiveUIDocument?.Document;
        if (activeDocument is null)
            return Result.Text.Failed("Revit has no active document open.");

        return args.Mode == RotatableFamilyMode.EditExisting
            ? EditExistingFamily(context, activeDocument, args)
            : CreateNewFamily(activeDocument, args);
    }

    private static IExtensionResult CreateNewFamily(Document activeDocument, FlexiRfaArgs args)
    {
        if (!File.Exists(args.TemplatePath))
            return Result.Text.Failed($"Template file not found: {args.TemplatePath}");

        if (string.IsNullOrWhiteSpace(args.NewFamilyName))
            return Result.Text.Failed("New family name is required.");

        var application = activeDocument.Application;
        var workingDirectory = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(workingDirectory);
        var workingFamilyPath = Path.Combine(workingDirectory, $"{args.NewFamilyName}.rfa");

        Document? familyDocument = null;

        try
        {
            File.Copy(args.TemplatePath, workingFamilyPath);
            familyDocument = application.OpenDocumentFile(workingFamilyPath);

            if (!familyDocument.IsFamilyDocument)
                return Result.Text.Failed("The selected template is not a family document.");

            SetFamilyCategory(familyDocument, args);
            RenameCurrentType(familyDocument, $"Rotatable {args.NewFamilyName}");

            var originError = SetOrigin(familyDocument, BuildOrigin(args));
            if (originError is not null)
                return Result.Text.Failed(originError);

            var error = ReplaceOrientationGeometry(familyDocument, args, out var geometryHost);
            if (error is not null)
                return Result.Text.Failed(error);

            familyDocument.LoadFamily(activeDocument, new FamilyLoadOptions());

            return Result.Text.Succeeded($"Created rotatable family '{args.NewFamilyName}' and loaded it into the active document. Geometry was written into '{geometryHost}'.");
        }
        catch (Exception ex)
        {
            return Result.Text.Failed($"Failed to create rotatable family: {ex.Message}");
        }
        finally
        {
            familyDocument?.Close(false);
            TryDeleteDirectory(workingDirectory);
        }
    }

    private static IExtensionResult EditExistingFamily(IRevitExtensionContext context, Document activeDocument, FlexiRfaArgs args)
    {
        var selectedIds = context.UIApplication.ActiveUIDocument.Selection.GetElementIds();
        var selectedInstance = selectedIds
            .Select(activeDocument.GetElement)
            .OfType<FamilyInstance>()
            .FirstOrDefault();

        if (selectedInstance is null)
            return Result.Text.Failed("Select a rotatable family instance in the model first.");

        var origin = selectedInstance.Symbol.LookupParameter(OriginParameterName)?.AsString();
        if (string.IsNullOrWhiteSpace(origin))
            return Result.Text.Failed($"The selected family has no '{OriginParameterName}' value, so it was not generated by this tool and cannot be edited.");

        var expectedOrigin = BuildOrigin(args);
        if (!string.Equals(origin, expectedOrigin, StringComparison.OrdinalIgnoreCase))
            return Result.Text.Failed($"The selected family was generated as '{origin}', but the current settings describe '{expectedOrigin}'. Match the settings to the family's origin, or create a new family instead.");

        var family = selectedInstance.Symbol.Family;
        var familyName = family.Name;
        Document? familyDocument = null;

        try
        {
            familyDocument = activeDocument.EditFamily(family);

            SetFamilyCategory(familyDocument, args);

            var originError = SetOrigin(familyDocument, BuildOrigin(args));
            if (originError is not null)
                return Result.Text.Failed(originError);

            var error = ReplaceOrientationGeometry(familyDocument, args, out var geometryHost);
            if (error is not null)
                return Result.Text.Failed(error);

            familyDocument.LoadFamily(activeDocument, new FamilyLoadOptions());

            return Result.Text.Succeeded($"Updated the extrusion on family '{familyName}'. Geometry was written into '{geometryHost}'.");
        }
        catch (Exception ex)
        {
            return Result.Text.Failed($"Failed to update rotatable family: {ex.Message}");
        }
        finally
        {
            familyDocument?.Close(false);
        }
    }

    // Text family parameter carried by the template; records how the family was generated.
    private const string OriginParameterName = "Origin";

    private static string BuildOrigin(FlexiRfaArgs args) => args.Preset == RotatableFamilyPreset.Custom
        ? $"Preset - Custom {args.ProfileShape}"
        : $"Preset - {args.Preset}";

    private static string? SetOrigin(Document familyDocument, string origin)
    {
        var familyManager = familyDocument.FamilyManager;
        var parameter = familyManager.get_Parameter(OriginParameterName);
        if (parameter is null)
            return $"The family has no '{OriginParameterName}' family parameter.";

        if (parameter.StorageType != StorageType.String)
            return $"The '{OriginParameterName}' family parameter must be of type Text.";

        if (parameter.IsDeterminedByFormula || parameter.IsReadOnly)
            return $"The '{OriginParameterName}' family parameter is read-only or driven by a formula.";

        using var originTransaction = new Transaction(familyDocument, "Set family origin");
        originTransaction.Start();

        if (familyManager.Types.Size == 0)
            familyManager.NewType("Rotatable");

        // The value is per type, so every type has to be stamped, not just the current one.
        foreach (var type in familyManager.Types.Cast<FamilyType>().ToList())
        {
            familyManager.CurrentType = type;
            familyManager.Set(parameter, origin);
        }

        originTransaction.Commit();
        return null;
    }

    private static void SetFamilyCategory(Document familyDocument, FlexiRfaArgs args)
    {
        if (string.IsNullOrWhiteSpace(args.FamilyCategory))
            return;

        using var categoryTransaction = new Transaction(familyDocument, "Set family category");
        categoryTransaction.Start();

        var category = familyDocument.Settings.Categories
            .Cast<Category>()
            .FirstOrDefault(c => c.Name.Equals(args.FamilyCategory, StringComparison.OrdinalIgnoreCase));
        if (category is not null)
            familyDocument.OwnerFamily.FamilyCategory = category;

        categoryTransaction.Commit();
    }

    private static void RenameCurrentType(Document familyDocument, string newTypeName)
    {
        var familyManager = familyDocument.FamilyManager;
        if (familyManager.CurrentType is null)
            return;

        using var renameTransaction = new Transaction(familyDocument, "Rename family type");
        renameTransaction.Start();
        familyManager.RenameCurrentType(newTypeName);
        renameTransaction.Commit();
    }

    // The nested "3D Orientation Family" is what the rotation parameters actually drive; geometry
    // added to the host family directly does not rotate, so the extrusion must live inside it.
    private static string? ReplaceOrientationGeometry(Document familyDocument, FlexiRfaArgs args, out string geometryHost)
    {
        geometryHost = "3D Orientation Family";

        var nestedInstance = new FilteredElementCollector(familyDocument)
            .OfClass(typeof(FamilyInstance))
            .Cast<FamilyInstance>()
            .FirstOrDefault(fi => fi.Symbol.Family.Name.Equals("3D Orientation Family", StringComparison.OrdinalIgnoreCase));

        if (nestedInstance is null)
            return "Could not find the nested '3D Orientation Family' in the family.";

        var nestedDocument = familyDocument.EditFamily(nestedInstance.Symbol.Family);

        // Orientation_CW rotates this further-nested geometry component, so replacing it with loose
        // extrusions would break the rotation; the forms are swapped inside it instead.
        var geometryInstance = new FilteredElementCollector(nestedDocument)
            .OfClass(typeof(FamilyInstance))
            .OfCategory(BuiltInCategory.OST_GenericModel)
            .Cast<FamilyInstance>()
            .FirstOrDefault();

        if (geometryInstance is null)
        {
            ReplaceForms(nestedDocument, args);
        }
        else
        {
            geometryHost = geometryInstance.Symbol.Family.Name;
            var geometryDocument = nestedDocument.EditFamily(geometryInstance.Symbol.Family);
            ReplaceForms(geometryDocument, args);
            geometryDocument.LoadFamily(nestedDocument, new FamilyLoadOptions());
            geometryDocument.Close(false);
        }

        nestedDocument.LoadFamily(familyDocument, new FamilyLoadOptions());
        nestedDocument.Close(false);

        return null;
    }

    private static void ReplaceForms(Document geometryDocument, FlexiRfaArgs args)
    {
        using var transaction = new Transaction(geometryDocument, "Replace 3D orientation geometry");
        transaction.Start();

        var existingForms = new FilteredElementCollector(geometryDocument)
            .OfClass(typeof(GenericForm))
            .ToElementIds();
        if (existingForms.Count > 0)
            geometryDocument.Delete(existingForms);

        if (args.Preset is RotatableFamilyPreset.ElectricalSocket or RotatableFamilyPreset.ElectricalSocketSingle or RotatableFamilyPreset.ElectricalSocketQuadruple)
            BuildElectricalSocket(geometryDocument, args.Preset);
        else if (args.Preset == RotatableFamilyPreset.RectangularLightFixture)
            BuildRectangularLightFixture(geometryDocument, args.LightFixtureLength, args.LightFixtureWidth);
        else
            BuildPresetGeometry(geometryDocument, ResolveDimensions(args));

        transaction.Commit();
    }

    private static void BuildPresetGeometry(Document nestedDocument, DimensionSet dimensions)
    {
        // Height is the profile's length dimension; Depth is the vertical extrusion amount.
        var profile = dimensions.ProfileShape == ExtrusionProfileShape.Cylinder
            ? BuildCircleProfile(dimensions.Diameter)
            : BuildRectangleProfile(dimensions.Width, dimensions.Height);
        var extrusionHeight = UnitUtils.ConvertToInternalUnits(dimensions.Depth, UnitTypeId.Millimeters);
        var flangeHeight = dimensions.FlangeDepth.HasValue
            ? UnitUtils.ConvertToInternalUnits(dimensions.FlangeDepth.Value, UnitTypeId.Millimeters)
            : 0;

        if (dimensions.SurfaceMounted)
        {
            // The wide plate meets the ceiling at the origin and the body stacks away from it.
            var plateSketchPlane = SketchPlane.Create(nestedDocument, GetHorizontalPlaneAtOrigin(nestedDocument));
            nestedDocument.FamilyCreate.NewExtrusion(true, BuildCircleProfile(dimensions.FlangeDiameter!.Value), plateSketchPlane, flangeHeight);

            var bodySketchPlane = SketchPlane.Create(nestedDocument, GetHorizontalPlaneAtOrigin(nestedDocument, flangeHeight));
            nestedDocument.FamilyCreate.NewExtrusion(true, profile, bodySketchPlane, extrusionHeight);
            return;
        }

        var sketchPlane = SketchPlane.Create(nestedDocument, GetHorizontalPlaneAtOrigin(nestedDocument));
        nestedDocument.FamilyCreate.NewExtrusion(true, profile, sketchPlane, extrusionHeight);

        // Second, wider/shallower extrusion stacked on top of the body, e.g. a downlight's ceiling trim ring.
        if (dimensions.FlangeDiameter.HasValue && dimensions.FlangeDepth.HasValue)
        {
            var flangeSketchPlane = SketchPlane.Create(nestedDocument, GetHorizontalPlaneAtOrigin(nestedDocument, extrusionHeight));
            nestedDocument.FamilyCreate.NewExtrusion(true, BuildCircleProfile(dimensions.FlangeDiameter.Value), flangeSketchPlane, flangeHeight);
        }
    }

    // Wall plate with a raised inner panel carrying 1, 2 (stacked) or 4 (2x2 grid) recessed 40 mm outlets.
    private static void BuildElectricalSocket(Document nestedDocument, RotatableFamilyPreset preset)
    {
        const double outletDiameterMm = 40;
        const double pinDiameterMm = 5;
        const double padSizeMm = 55;

        var isQuadruple = preset == RotatableFamilyPreset.ElectricalSocketQuadruple;
        var plateWidthMm = isQuadruple ? 120 : 85;
        var plateHeightMm = preset == RotatableFamilyPreset.ElectricalSocketSingle ? 85 : 120;

        var faceDepthMm = 8;
        // 20 mm is the depth at which the pocket's wall actually reads under Revit's flat shading; shallower pads
        // render as a flat surface with only an outline.
        var panelOrPadDepthMm = 20;
        // The quadruple box is much deeper (device box), so most of the extra depth goes into the back layer.
        var backDepthMm = isQuadruple ? 40 - faceDepthMm - panelOrPadDepthMm : 2;
        // At least this much of the back layer stays a plain, uncut slab, so the pin holes never reach the visible
        // backside of the socket.
        var backClosureMm = Math.Min(2, backDepthMm);
        var backCutDepthMm = backDepthMm - backClosureMm;

        var backClosureDepth = UnitUtils.ConvertToInternalUnits(backClosureMm, UnitTypeId.Millimeters);
        var backCutDepth = UnitUtils.ConvertToInternalUnits(backCutDepthMm, UnitTypeId.Millimeters);
        var faceDepth = UnitUtils.ConvertToInternalUnits(faceDepthMm, UnitTypeId.Millimeters);
        var panelOrPadDepth = UnitUtils.ConvertToInternalUnits(panelOrPadDepthMm, UnitTypeId.Millimeters);
        var pinSpacing = UnitUtils.ConvertToInternalUnits(9.5, UnitTypeId.Millimeters);
        var outletCentres = GetOutletCentres(preset, plateHeightMm);

        // The outward-facing back slab is always a plain, uncut solid.
        var backSketchPlane = SketchPlane.Create(nestedDocument, GetHorizontalPlaneAtOrigin(nestedDocument));
        nestedDocument.FamilyCreate.NewExtrusion(true, BuildRoundedRectangleProfile(plateWidthMm, plateHeightMm, 8), backSketchPlane, backClosureDepth);

        // Pin holes cut through the remaining (inner) portion of the back layer, so they read as a real, deep pit
        // under flat shading without ever punching through to the visible backside.
        if (backCutDepthMm > 0)
        {
            var backInnerProfile = BuildRoundedRectangleProfile(plateWidthMm, plateHeightMm, 8);
            foreach (var (verticalOffset, horizontalOffset) in outletCentres)
            {
                foreach (var pinOffset in new[] { pinSpacing, -pinSpacing })
                    backInnerProfile.Append(BuildCircleLoop(pinDiameterMm, verticalOffset, horizontalOffset + pinOffset));
            }

            var backInnerSketchPlane = SketchPlane.Create(nestedDocument, GetHorizontalPlaneAtOrigin(nestedDocument, backClosureDepth));
            nestedDocument.FamilyCreate.NewExtrusion(true, backInnerProfile, backInnerSketchPlane, backCutDepth);
        }

        // Pin holes punch through this layer too, continuing the through-hole started in the back layer.
        var faceProfile = BuildRoundedRectangleProfile(plateWidthMm, plateHeightMm, 8);
        foreach (var (verticalOffset, horizontalOffset) in outletCentres)
        {
            foreach (var pinOffset in new[] { pinSpacing, -pinSpacing })
                faceProfile.Append(BuildCircleLoop(pinDiameterMm, verticalOffset, horizontalOffset + pinOffset));
        }

        var faceSketchPlane = SketchPlane.Create(nestedDocument, GetHorizontalPlaneAtOrigin(nestedDocument, backClosureDepth + backCutDepth));
        nestedDocument.FamilyCreate.NewExtrusion(true, faceProfile, faceSketchPlane, faceDepth);

        var topSketchPlane = SketchPlane.Create(nestedDocument, GetHorizontalPlaneAtOrigin(nestedDocument, backClosureDepth + backCutDepth + faceDepth));

        // Each outlet gets its own small raised pad with a hole cut through it, so the outlet itself reads as an
        // individual recessed pocket rather than sharing one continuous frame with its neighbours.
        foreach (var (verticalOffset, horizontalOffset) in outletCentres)
        {
            var padProfile = BuildRoundedRectangleProfile(padSizeMm, padSizeMm, 6, verticalOffset, horizontalOffset);
            padProfile.Append(BuildCircleLoop(outletDiameterMm, verticalOffset, horizontalOffset));
            nestedDocument.FamilyCreate.NewExtrusion(true, padProfile, topSketchPlane, panelOrPadDepth);
        }
    }

    // Surface-mounted batten luminaire: a shallow housing against the ceiling with a narrower diffuser below it.
    private static void BuildRectangularLightFixture(Document nestedDocument, double lengthMm, double widthMm)
    {
        const double housingDepthMm = 30;
        const double diffuserDepthMm = 25;
        const double diffuserInsetMm = 12;

        var length = lengthMm > 0 ? lengthMm : 1200;
        var width = widthMm > 0 ? widthMm : 100;
        var housingDepth = UnitUtils.ConvertToInternalUnits(housingDepthMm, UnitTypeId.Millimeters);
        var diffuserDepth = UnitUtils.ConvertToInternalUnits(diffuserDepthMm, UnitTypeId.Millimeters);

        var housingSketchPlane = SketchPlane.Create(nestedDocument, GetHorizontalPlaneAtOrigin(nestedDocument));
        nestedDocument.FamilyCreate.NewExtrusion(true, BuildRoundedRectangleProfile(width, length, 8), housingSketchPlane, housingDepth);

        var diffuserSketchPlane = SketchPlane.Create(nestedDocument, GetHorizontalPlaneAtOrigin(nestedDocument, housingDepth));
        nestedDocument.FamilyCreate.NewExtrusion(true, BuildRoundedRectangleProfile(width - diffuserInsetMm, length - diffuserInsetMm, 6), diffuserSketchPlane, diffuserDepth);
    }

    // Outlet centres in internal units: single sits at the origin, double stacks vertically, quadruple forms a 2x2 grid.
    private static IReadOnlyList<(double VerticalOffset, double HorizontalOffset)> GetOutletCentres(RotatableFamilyPreset preset, double plateHeightMm)
    {
        var quarterHeight = UnitUtils.ConvertToInternalUnits(plateHeightMm / 4, UnitTypeId.Millimeters);

        return preset switch
        {
            RotatableFamilyPreset.ElectricalSocketSingle => [(0d, 0d)],
            RotatableFamilyPreset.ElectricalSocketQuadruple =>
            [
                (quarterHeight, quarterHeight),
                (quarterHeight, -quarterHeight),
                (-quarterHeight, quarterHeight),
                (-quarterHeight, -quarterHeight),
            ],
            _ => [(quarterHeight, 0d), (-quarterHeight, 0d)],
        };
    }

    private static void TryDeleteDirectory(string path)
    {
        try
        {
            Directory.Delete(path, recursive: true);
        }
        catch (IOException)
        {
        }
    }

    private readonly record struct DimensionSet(ExtrusionProfileShape ProfileShape, double Width, double Height, double Diameter, double Depth, double? FlangeDiameter = null, double? FlangeDepth = null, bool SurfaceMounted = false);

    // Preset dimensions win outright; the custom fields keep stale values while hidden, so they are ignored here.
    private static DimensionSet ResolveDimensions(FlexiRfaArgs args)
    {
        var preset = GetPresetDefaults(args.Preset);
        if (preset is null)
            return new DimensionSet(args.ProfileShape, args.Width, args.Height, args.Diameter, args.Depth);

        var diameter = preset.Value.Diameter;
        var flangeDiameter = preset.Value.FlangeDiameter;
        var presetDiameter = args.Preset switch
        {
            RotatableFamilyPreset.Downlight => args.DownlightDiameter,
            RotatableFamilyPreset.SmokeDetector => args.SmokeDetectorDiameter,
            _ => 0,
        };

        if (presetDiameter > 0)
        {
            // Keep the preset's lip width by growing the flange with the body.
            var lipWidth = preset.Value.FlangeDiameter!.Value - preset.Value.Diameter;
            diameter = presetDiameter;
            flangeDiameter = diameter + lipWidth;
        }

        return preset.Value with { Diameter = diameter, FlangeDiameter = flangeDiameter };
    }

    private static DimensionSet? GetPresetDefaults(RotatableFamilyPreset preset) => preset switch
    {
        // Narrower recessed body plus a wider, shallow trim ring sitting on top of it.
        RotatableFamilyPreset.Downlight => new DimensionSet(ExtrusionProfileShape.Cylinder, 0, 0, 150, 100, FlangeDiameter: 220, FlangeDepth: 15),
        // Shallow sensor chamber hanging below the wider plate that sits against the ceiling.
        RotatableFamilyPreset.SmokeDetector => new DimensionSet(ExtrusionProfileShape.Cylinder, 0, 0, 85, 20, FlangeDiameter: 110, FlangeDepth: 15, SurfaceMounted: true),
        _ => null,
    };

    // Reference Level sits at the family origin, matching the "Center (Front/Back)" / "Center (Left/Right)" planes.
    private static Plane GetHorizontalPlaneAtOrigin(Document familyDocument, double zOffset = 0)
    {
        var level = new FilteredElementCollector(familyDocument)
            .OfClass(typeof(Level))
            .Cast<Level>()
            .OrderBy(l => Math.Abs(l.Elevation))
            .FirstOrDefault();

        var elevation = level?.Elevation ?? 0;
        return Plane.CreateByNormalAndOrigin(XYZ.BasisZ, new XYZ(0, 0, elevation + zOffset));
    }

    private static CurveArrArray BuildRectangleProfile(double widthMm, double depthMm)
    {
        var halfWidth = UnitUtils.ConvertToInternalUnits(widthMm, UnitTypeId.Millimeters) / 2;
        var halfDepth = UnitUtils.ConvertToInternalUnits(depthMm, UnitTypeId.Millimeters) / 2;

        var p0 = new XYZ(-halfWidth, -halfDepth, 0);
        var p1 = new XYZ(halfWidth, -halfDepth, 0);
        var p2 = new XYZ(halfWidth, halfDepth, 0);
        var p3 = new XYZ(-halfWidth, halfDepth, 0);

        var loop = new CurveArray();
        loop.Append(Line.CreateBound(p0, p1));
        loop.Append(Line.CreateBound(p1, p2));
        loop.Append(Line.CreateBound(p2, p3));
        loop.Append(Line.CreateBound(p3, p0));

        var profile = new CurveArrArray();
        profile.Append(loop);
        return profile;
    }

    private static CurveArrArray BuildRoundedRectangleProfile(double widthMm, double depthMm, double cornerRadiusMm, double verticalOffset = 0, double horizontalOffset = 0)
    {
        var halfWidth = UnitUtils.ConvertToInternalUnits(widthMm, UnitTypeId.Millimeters) / 2;
        var halfDepth = UnitUtils.ConvertToInternalUnits(depthMm, UnitTypeId.Millimeters) / 2;
        var r = Math.Min(UnitUtils.ConvertToInternalUnits(cornerRadiusMm, UnitTypeId.Millimeters), Math.Min(halfWidth, halfDepth) - 1e-6);
        var centre = new XYZ(horizontalOffset, verticalOffset, 0);

        if (r <= 0)
            return BuildRectangleProfile(widthMm, depthMm);

        var loop = new CurveArray();

        loop.Append(Line.CreateBound(centre + new XYZ(-halfWidth + r, -halfDepth, 0), centre + new XYZ(halfWidth - r, -halfDepth, 0)));
        loop.Append(CornerArc(centre + new XYZ(halfWidth - r, -halfDepth + r, 0), centre + new XYZ(halfWidth - r, -halfDepth, 0), centre + new XYZ(halfWidth, -halfDepth + r, 0)));

        loop.Append(Line.CreateBound(centre + new XYZ(halfWidth, -halfDepth + r, 0), centre + new XYZ(halfWidth, halfDepth - r, 0)));
        loop.Append(CornerArc(centre + new XYZ(halfWidth - r, halfDepth - r, 0), centre + new XYZ(halfWidth, halfDepth - r, 0), centre + new XYZ(halfWidth - r, halfDepth, 0)));

        loop.Append(Line.CreateBound(centre + new XYZ(halfWidth - r, halfDepth, 0), centre + new XYZ(-halfWidth + r, halfDepth, 0)));
        loop.Append(CornerArc(centre + new XYZ(-halfWidth + r, halfDepth - r, 0), centre + new XYZ(-halfWidth + r, halfDepth, 0), centre + new XYZ(-halfWidth, halfDepth - r, 0)));

        loop.Append(Line.CreateBound(centre + new XYZ(-halfWidth, halfDepth - r, 0), centre + new XYZ(-halfWidth, -halfDepth + r, 0)));
        loop.Append(CornerArc(centre + new XYZ(-halfWidth + r, -halfDepth + r, 0), centre + new XYZ(-halfWidth, -halfDepth + r, 0), centre + new XYZ(-halfWidth + r, -halfDepth, 0)));

        var profile = new CurveArrArray();
        profile.Append(loop);
        return profile;

        Arc CornerArc(XYZ arcCentre, XYZ start, XYZ end)
        {
            var mid = arcCentre + (start - arcCentre + (end - arcCentre)).Normalize().Multiply(r);
            return Arc.Create(start, end, mid);
        }
    }

    private static CurveArrArray BuildCircleProfile(double diameterMm, double verticalOffset = 0, double horizontalOffset = 0)
    {
        var profile = new CurveArrArray();
        profile.Append(BuildCircleLoop(diameterMm, verticalOffset, horizontalOffset));
        return profile;
    }

    private static CurveArray BuildCircleLoop(double diameterMm, double verticalOffset = 0, double horizontalOffset = 0)
    {
        var radius = UnitUtils.ConvertToInternalUnits(diameterMm, UnitTypeId.Millimeters) / 2;
        var centre = new XYZ(horizontalOffset, verticalOffset, 0);

        var loop = new CurveArray();
        loop.Append(Arc.Create(centre, radius, 0, Math.PI, XYZ.BasisX, XYZ.BasisY));
        loop.Append(Arc.Create(centre, radius, Math.PI, 2 * Math.PI, XYZ.BasisX, XYZ.BasisY));
        return loop;
    }
}

// Always overwrite the existing project family when re-running the extension.
file sealed class FamilyLoadOptions : IFamilyLoadOptions
{
    public bool OnFamilyFound(bool familyInUse, out bool overwriteParameterValues)
    {
        overwriteParameterValues = true;
        return true;
    }

    public bool OnSharedFamilyFound(Family sharedFamily, bool familyInUse, out FamilySource source, out bool overwriteParameterValues)
    {
        source = FamilySource.Family;
        overwriteParameterValues = true;
        return true;
    }
}