<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ExtensionId>FlexiRfa</ExtensionId>
    <Authors>AEC AB</Authors>
    <Version>0.0.1</Version>
    <Title>FlexiRfa</Title>
    <Description>FlexiRfa Description</Description>
    <PackageTags>Revit;Assistant;Extension;Automation</PackageTags>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageIconUrl></PackageIconUrl>
    <!-- 
    Adjust MainRevitVersion to get IntelliSense for the correct version do a 
    dotnet restore to restore the correct nuget packages for the selected Revit version.
    -->
    <MainRevitVersion Condition="'$(Configuration)' == 'Debug'">2026</MainRevitVersion>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <Import Project=".\Configurations.targets" />

  <ItemGroup>
    <None Include="Icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>